version: 2
updates:
  - package-ecosystem: 'yarn'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '16:00'
      timezone: 'UTC'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '16:00'
      timezone: 'UTC'
