extends:
  - "@commitlint/config-conventional"

rules:
  type-enum:
    - 2
    - always
    - [
        "feat",
        "fix",
        "chore",
        "docs",
        "style",
        "build",
        "tech"
      ]

  scope-empty:
    - 2
    - always

  header-max-length:
    - 2
    - always
    - 72

  subject-empty:
    - 2
    - never

  subject-case:
    - 1
    - never
    - [
        "sentence-case",
        "lower-case"
      ]
